CREATE DATABASE SCHOOL;
DROP DATABASE SCHOOL;

SHOW DATABASES;

USE SCHOOL;


CREATE TABLE STUDENTS (
        ID_STUDENT INT PRIMARY KEY AUTO_INCREMENT,
        FIRSTNAME VARCHAR(50),
        LASTNAME VARCHAR(50),
        DNI VARCHAR(20),        
        ADDRESS VARCHAR(100),
        TELEPHONE CHAR(20)
    );
DROP TABLE STUDENTS;

SELECT * FROM STUDENTS;

CREATE TABLE SUBJECTS (
        ID_SUBJECT INT PRIMARY KEY AUTO_INCREMENT,
        NAME_S VARCHAR(50),
        DESCRIPTION_S VARCHAR(100),
        YEAR_S INT,
        DURATION VARCHAR(50),
        TEACHER VARCHAR(50)
        );
DROP TABLE SUBJECTS;   

SELECT * FROM SUBJECTS;

CREATE TABLE REGISTERS(
        ID_REGISTER INT PRIMARY KEY AUTO_INCREMENT,
        ID_STUDENT INT NOT NULL,
        ID_SUBJECT INT NOT NULL,
        REGISTER_DATE DATE,
        FOREIGN KEY (ID_STUDENT) REFERENCES STUDENTS(ID_STUDENT),
        FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS(ID_SUBJECT)        
        );
DROP TABLE REGISTERS;

SELECT * FROM REGISTERS;

        
insert into STUDENTS (FIRSTNAME,LASTNAME,DNI,ADDRESS,TELEPHONE)
	values ('Santiago', 'Perez','78945612K','camposancos570',987654321);
insert into STUDENTS (FIRSTNAME,LASTNAME,DNI,ADDRESS,TELEPHONE)
	values ('Sofi', 'Perez','75875612K','camposan70',987655555);
insert into STUDENTS (FIRSTNAME,LASTNAME,DNI,ADDRESS,TELEPHONE)
	values ('Santiago', 'Perez','78945612K','camposancos570',987654321);
insert into STUDENTS (FIRSTNAME,LASTNAME,DNI,ADDRESS,TELEPHONE)
	values ('Sofi', 'Perez','75875612K','camposan70',987655555);
insert into STUDENTS (FIRSTNAME,LASTNAME,DNI,ADDRESS,TELEPHONE)
	values ('Santiago', 'Perez','78945612K','camposancos570',987654321);
insert into STUDENTS (FIRSTNAME,LASTNAME,DNI,ADDRESS,TELEPHONE)
	values ('Sofi', 'Perez','75875612K','camposan70',987655555);

insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');
insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');
insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');
insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');
insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');
insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');
insert into SUBJECTS (NAME_S,DESCRIPTION_S,YEAR_S,DURATION,TEACHER)
	values ('Lengua Extranjera Profesional: Ingles 1', '1SIO','2022/2023','MARIA DEL CORAL GARCIA HIDALGO');

    
insert into REGISTERS (ID_STUDENT,ID_SUBJECT,REGISTER_DATE) values (1,5,'2022-03-25');
insert into REGISTERS (ID_STUDENT,ID_SUBJECT,REGISTER_DATE) values (1,5,'2022-03-25');
insert into REGISTERS (ID_STUDENT,ID_SUBJECT,REGISTER_DATE) values (1,5,'2022-03-25');
insert into REGISTERS (ID_STUDENT,ID_SUBJECT,REGISTER_DATE) values (1,5,'2022-03-25');


alter table STUDENTS add image varchar(200);
